# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $alt Mod1
set $mod Mod4
set $mod2 Mod3
set $ctrl Control

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

hide_edge_borders both
#workspace_layout tabbed

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill
bindsym $alt+F4 kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+odiaeresis move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+g split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

{% if desktop %}
set $displayleft HDMI-0
set $displayright DVI-I-1

set $lws1 workspace 1 web
set $lws2 workspace 2 files
set $lws3 workspace 3
set $lws4 workspace 4
set $lws5 workspace 5
set $lws6 workspace 6
set $lws7 workspace 7
set $lws8 workspace 8
set $lws9 workspace 9
set $lws10 workspace 10

set $rws1 workspace 11 irc
set $rws2 workspace 12 beat
set $rws3 workspace 13
set $rws4 workspace 14
set $rws5 workspace 15
set $rws6 workspace 16
set $rws7 workspace 17
set $rws8 workspace 18
set $rws9 workspace 19
set $rws10 workspace 20
{% elif laptop %}
set $displayleft eDP1
set $displayright DP2
# vga=DP2, displayport=?

set $lws1 workspace 1 web
set $lws2 workspace 2 irc
set $lws3 workspace 3 beat
set $lws4 workspace 4 term
set $lws5 workspace 5
set $lws6 workspace 6
set $lws7 workspace 7
set $lws8 workspace 8
set $lws9 workspace 9
set $lws10 workspace 10

set $rws1 workspace 11
set $rws2 workspace 12
set $rws3 workspace 13
set $rws4 workspace 14
set $rws5 workspace 15
set $rws6 workspace 16
set $rws7 workspace 17
set $rws8 workspace 18
set $rws9 workspace 19
set $rws10 workspace 20
{% elif bp %}
set $displayleft DVI-0
set $displayright HDMI2

set $lws1 workspace 1 files
set $lws2 workspace 2 dev
set $lws3 workspace 3
set $lws4 workspace 4
set $lws5 workspace 5
set $lws6 workspace 6
set $lws7 workspace 7
set $lws8 workspace 8
set $lws9 workspace 9
set $lws10 workspace 10

set $rws1 workspace 11 web
set $rws2 workspace 12 dev
set $rws3 workspace 13
set $rws4 workspace 14
set $rws5 workspace 15
set $rws6 workspace 16
set $rws7 workspace 17
set $rws8 workspace 18
set $rws9 workspace 19
set $rws10 workspace 20
{% endif %}

workspace 1 output $displayleft
workspace 2 output $displayleft
workspace 3 output $displayleft
workspace 4 output $displayleft
workspace 5 output $displayleft
workspace 6 output $displayleft
workspace 7 output $displayleft
workspace 8 output $displayleft
workspace 9 output $displayleft
workspace 10 output $displayleft

workspace 11 output $displayright
workspace 12 output $displayright
workspace 13 output $displayright
workspace 14 output $displayright
workspace 15 output $displayright
workspace 16 output $displayright
workspace 17 output $displayright
workspace 18 output $displayright
workspace 19 output $displayright
workspace 20 output $displayright

bindsym $mod+1 $lws1
bindsym $mod+2 $lws2
bindsym $mod+3 $lws3
bindsym $mod+4 $lws4
bindsym $mod+5 $lws5
bindsym $mod+6 $lws6
bindsym $mod+7 $lws7
bindsym $mod+8 $lws8
bindsym $mod+9 $lws9
bindsym $mod+0 $lws10

bindsym $mod2+1 $rws1
bindsym $mod2+2 $rws2
bindsym $mod2+3 $rws3
bindsym $mod2+4 $rws4
bindsym $mod2+5 $rws5
bindsym $mod2+6 $rws6
bindsym $mod2+7 $rws7
bindsym $mod2+8 $rws8
bindsym $mod2+9 $rws9
bindsym $mod2+0 $rws10

bindsym $mod+comma workspace prev
bindsym $mod+period workspace next
bindsym $mod+Tab workspace back_and_forth
bindsym $mod2+comma workspace prev
bindsym $mod2+period workspace next
bindsym $mod2+Tab workspace back_and_forth

# move focused container to workspace
bindsym $mod+Shift+1 move container to $lws1; $lws1
bindsym $mod+Shift+2 move container to $lws2; $lws2
bindsym $mod+Shift+3 move container to $lws3; $lws3
bindsym $mod+Shift+4 move container to $lws4; $lws4
bindsym $mod+Shift+5 move container to $lws5; $lws5
bindsym $mod+Shift+6 move container to $lws6; $lws6
bindsym $mod+Shift+7 move container to $lws7; $lws7
bindsym $mod+Shift+8 move container to $lws8; $lws8
bindsym $mod+Shift+9 move container to $lws9; $lws9
bindsym $mod+Shift+0 move container to $lws10; $lws10

bindsym $mod2+Shift+1 move container to $rws1; $rws1
bindsym $mod2+Shift+2 move container to $rws2; $rws2
bindsym $mod2+Shift+3 move container to $rws3; $rws3
bindsym $mod2+Shift+4 move container to $rws4; $rws4
bindsym $mod2+Shift+5 move container to $rws5; $rws5
bindsym $mod2+Shift+6 move container to $rws6; $rws6
bindsym $mod2+Shift+7 move container to $rws7; $rws7
bindsym $mod2+Shift+8 move container to $rws8; $rws8
bindsym $mod2+Shift+9 move container to $rws9; $rws9
bindsym $mod2+Shift+0 move container to $rws10; $rws10

# turn the terminal bell off
exec xset b off
exec --no-startup-id nm-applet
exec --no-startup-id seafile-applet

{% if desktop %}
exec i3-msg "$lws1; layout tabbed; exec chromium; exec thunderbird"
exec i3-msg "$lws2; exec nemo --no-desktop"
exec i3-msg "$rws1; exec urxvt -e weechat"
exec i3-msg "$rws2; layout tabbed; exec urxvt -e ncmpcpp; exec spotify; exec pavucontrol"

for_window [title=".* Chromium$"] move $lws1
for_window [title="^Spotify$"] move $rws2
{% elif laptop %}
exec ~/bin/i3-battery.sh

exec --no-startup-id my-i3lock
exec --no-startup-id xautolock -detectsleep -time 10 -locker 'my-i3lock'
exec --no-startup-id feh --bg-center /home/moritz/Pictures/wallpaper/current.whatever
exec --no-startup-id /home/moritz/bin/disable_touchpad.sh
exec i3-msg "$lws1; exec chromium"
exec i3-msg "$lws2; exec urxvt -e weechat"
exec i3-msg "$lws3; exec urxvt -e ncmpcpp"
exec i3-msg "$lws4; exec urxvt -e zsh -i"

for_window [title=".* Chromium$"] move $lws1
{% elif bp %}
exec --no-startup-id feh --bg-center /home/moritz/Pictures/wallpaper/current.whatever
{% endif %}

# reload the configuration file
bindsym $mod+Shift+c exec "/home/moritz/bin/i3-conf-update.sh; i3-msg reload"
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r exec "/home/moritz/bin/i3-conf-update.sh; i3-msg restart"
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

set $locker my-i3lock && sleep 1
set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id $locker, mode "default"
    bindsym e exec --no-startup-id i3-msg exit, mode "default"
    bindsym s exec --no-startup-id $locker && systemctl suspend, mode "default"
    bindsym h exec --no-startup-id $locker && systemctl hibernate, mode "default"
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"  

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+End mode "$mode_system"
bindsym $ctrl+$alt+l exec $locker

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym odiaeresis resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# pulse audio volume control
bindsym XF86AudioLowerVolume exec "/home/moritz/bin/my-volume.sh down"
bindsym XF86AudioRaiseVolume exec "/home/moritz/bin/my-volume.sh up"
bindsym XF86AudioMute exec "/home/moritz/bin/my-volume.sh toggle"
bindsym Print exec "sleep 0.2; scrot /tmp/screen.png"
bindsym Shift+Print exec "sleep 0.2; scrot -sb /tmp/screen.png"
bindsym $mod+Ctrl+O exec "/home/moritz/bin/awoxl off"
bindsym $mod+Ctrl+P exec "/home/moritz/bin/awoxl on"
bindsym $mod+Ctrl+L exec "/home/moritz/bin/awoxl white 11"

{% if desktop %}
# This does not seem to work :/
#bindsym $mod+F3 exec "xdotool key XF86AudioLowerVolume"
#bindsym $mod+F4 exec "xdotool key XF86AudioRaiseVolume"
#bindsym $mod+F2 exec "xdotool key XF86AudioMute"

bindsym $mod+F3 exec --no-startup-id "/home/moritz/bin/my-volume.sh down"
bindsym $mod+F4 exec --no-startup-id "/home/moritz/bin/my-volume.sh up"
bindsym $mod+F2 exec --no-startup-id "/home/moritz/bin/my-volume.sh toggle"

bindsym --whole-window $mod+button5 exec --no-startup-id "/home/moritz/bin/my-volume.sh down"
bindsym --whole-window $mod+button4 exec --no-startup-id "/home/moritz/bin/my-volume.sh up"
bindsym --whole-window $mod+button2 exec --no-startup-id "/home/moritz/bin/my-volume.sh toggle"
{% elif laptop %}
bindsym XF86MonBrightnessUp exec /usr/bin/xbacklight -inc 10
bindsym XF86MonBrightnessDown exec /usr/bin/xbacklight -dec 5
{% elif bp %}
bindsym $mod+F3 exec --no-startup-id "/home/moritz/bin/my-volume.sh down"
bindsym $mod+F4 exec --no-startup-id "/home/moritz/bin/my-volume.sh up"
bindsym $mod+F2 exec --no-startup-id "/home/moritz/bin/my-volume.sh toggle"
{% endif %}

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
{% if bp %}
    output DVI-1-0
{% endif %}
    status_command py3status -c ~/.i3/i3status.conf
}

{% if bp %}
bar {
    output HDMI2
    status_command py3status -c ~/.i3/i3status_clean.conf
}
{% endif %}
